config/routes.rb
Rails.application.routes.draw do
 resources :troncs
 match 'staffhours/all/edit' => 'staffhours#edit_all', :as => :edit_all, :via => :get
 match 'staffhours/all/edit_last' => 'staffhours#edit_last', :as => :edit_last, :via => :get
 match 'staffhours/all/edit_next' => 'staffhours#edit_next', :as => :edit_next, :via => :get
 match 'staffhours/all' => 'staffhours#update_all', :as => :update_all, :via => :put
 match 'staffhours/show_team' => 'staffhours#show_team', :as => :show_team, :via => :get
 match 'staffhours/accrued_vacation' => 'staffhours#accrued_vacation', :as => :accrued_vacation, :via => :get

 resources :staffhours
 resources :accruel_rates
  resources :staffs do
    resources :staffevents
  end  
  resources :expenses do
      collection { get :show_many };
      collection { get :add_new }
    end
  resources :dailystats
  resources :dailybanks do
    member do
       post 'submit_comment';
       post 'mgmt_lock';
       post 'lock_float';
       post 'lock_event';
       post 'create_new_expense_record';
       post 'put_to_mgmt_review';
       post 'no_expenses_to_add';
       post 'mgmt_recalculate'; 
       get 'mgmt_review';
    end
     resources :expenses
  end
 
  resources :exemptions
  resources :functions
  resources :cashfloats do
      collection { post :validate };
      collection { get :show_float }
    end

  get 'daily_checks/today'
  get 'daily_checks/yesterday'
  get 'daily_checks/history'

  get 'messages/new'
  post 'messages/create'   => 'messages#create'
  post 'customers/subscribe'   => 'customers#subscribe'

  resources :errors
  resources :users
  resources :customers
  resources :bookings do
      collection { post :booking_confirmation };
      collection { post :booking_cancellation };
      collection { post :booking_get_times };
      collection { post :booking_advanced };
      collection { post :mgmt_edit };
    end  
  resources :tables do
      collection { post :booking_enquiry }
    end  
  resources :rdetails
  resources :restaurants
  resources :accounts
  resources :enquiries
  resources :categories
  resources :products do
    		 collection { post :import }
       end
   resources :sessions, only: [:new, :create, :destroy]
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

  root 'static_pages#hfsk_home'
 
 
 
  get '/index_full' => 'dailybanks#index_full'
  get '/index_ongoing' => 'dailybanks#index_ongoing'
  get '/latest' => 'dailybanks#latest'
  get '/history' => 'dailybanks#history'
  get '/history_week' => 'dailybanks#history_week'
  get '/history_month' => 'dailybanks#history_month'
  get '/tax_quarter' => 'dailybanks#tax_quarter'
  get '/card_tips_report' => 'dailybanks#card_tips_report'
  get '/home' => 'static_pages#home'
  get '/heat_at_home' => 'static_pages#hfsk_heat_at_home'
  get '/help' => 'static_pages#help'
  get '/booking_enquiry' => 'static_pages#booking_enquiry'
  get '/new_booking_enquiry' => 'static_pages#new_booking_enquiry'
  get '/booking_advanced' => 'static_pages#booking_advanced'
  get '/function_room_enquiry' => 'static_pages#function_room_enquiry'
  get '/download_menu_pdf' => 'static_pages#download_menu_pdf'
  get '/download_function_pdf' => 'static_pages#download_function_pdf'
  get '/download_engine_tandc_pdf' => 'static_pages#download_engine_tandc_pdf'
  get '/download_festive_pdf' => 'static_pages#download_festive_pdf'
  get '/basic_report' => 'bookings#basic_report'
  get '/deposit_report' => 'bookings#deposit_report'
  get '/confirmation_report' => 'bookings#confirmation_report'
  get '/confirmation_report_month' => 'bookings#confirmation_report_month'
  get '/day_to_view_bookings_report' => 'bookings#day_to_view_bookings_report'
  get '/calendar' => 'bookings#calendar'
  get '/availability' => 'bookings#availability'
  get '/availability_detail' => 'bookings#availability_detail'
  get '/all_customers' => 'customers#all_customers'
  get '/all_bookings' => 'bookings#all_bookings'
  get '/download_bookings_pdf' => "bookings#download_bookings_pdf"
  get '/download_bookings_evening_pdf' => "bookings#download_bookings_evening_pdf"
  get '/mgmt_edit_booking' => 'bookings#mgmt_edit'
  get '/search_bookings' => 'bookings#search_bookings' 
  get '/cashfloats_validate' => 'cashfloats#validate'  
  get '/download_end_of_night_pdf' => "dailybanks#download_end_of_night_pdf" 
  get '/download_dailybank_tax_accounting_pdf' => "dailybanks#download_dailybank_tax_accounting_pdf"
  get '/download_card_tips_report_pdf' => "dailybanks#download_card_tips_report_pdf" 
  get '/download_expenses_report_pdf' => "expenses#download_expenses_report_pdf" 
  get '/download_tronc_allocation_report_pdf' => "staffhours#download_tronc_allocation_report_pdf" 
  get '/download_vacation_accruel_report_pdf' => "staffhours#download_vacation_accruel_report_pdf" 
  
  
  get '/hfsk_home' => 'static_pages#hfsk_home'
  get '/hfsk_about' => 'static_pages#hfsk_about'
  get '/hfsk_blog' => 'static_pages#hfsk_blog'
  get '/hfsk_booking' => 'static_pages#booking_enquiry'
  get '/hfsk_location' => 'static_pages#hfsk_location'
  get '/hfsk_pay_deposit' => 'static_pages#hfsk_pay_deposit'
  get '/hfsk_deposit_terms' => 'static_pages#hfsk_deposit_terms'
  get '/hfsk_confirm_deposit' => 'static_pages#hfsk_confirm_deposit'
  get '/hfsk_get_in_touch' => 'static_pages#hfsk_get_in_touch'
  get '/hfsk_careers' => 'static_pages#hfsk_careers'
  get '/hfsk_menu' => 'static_pages#hfsk_menu'
  get '/hfsk_holiday_season' => 'static_pages#hfsk_holiday_season'
  get '/hfsk_gift_vouchers' => 'static_pages#hfsk_gift_vouchers'
  get '/hfsk_find_my_booking' => 'static_pages#hfsk_find_my_booking'
  get '/hfsk_heat_at_home' => 'static_pages#hfsk_heat_at_home'
  
  get '/hfsk_home_new' => 'static_pages#hfsk_home_new'
  get '/new_booking_enquiry_new' => 'static_pages#new_booking_enquiry_new'
  get '/hfsk_location_new' => 'static_pages#hfsk_location_new'
  get '/hfsk_menu_new' => 'static_pages#hfsk_menu_new'
  get '/hfsk_what_we_do' => 'static_pages#hfsk_what_we_do'
  get '/hfsk_get_in_touch_new' => 'static_pages#hfsk_get_in_touch_new'
  get '/hfsk_heat_at_home' => 'static_pages#hfsk_heat_at_home'
 
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/day_picker"
  get "static_pages/booking_enquiry"
  get "static_pages/new_booking_enquiry"
  get "static_pages/booking_advanced"
  get "static_pages/function_room_enquiry"
  get "static_pages/booking_confirm"  
  
  get "static_pages/hfsk_home"
  get "static_pages/hfsk_blog"
  get "static_pages/hfsk_about"
  get "static_pages/hfsk_location"
  get "static_pages/hfsk_pay_deposit"
  get "static_pages/hfsk_deposit_terms"
  get "static_pages/hfsk_confirm_deposit"
  get "static_pages/hfsk_get_in_touch"
  get "static_pages/hfsk_careers"
  get "static_pages/hfsk_menu"
  get "static_pages/hfsk_holiday_season"
  get "sessions/new"
  get "static_pages/new_booking_enquiry_new"
  get "send_customer_booking_mail", to: 'static_pages#send_customer_booking_mail', as: :send_customer_booking_mail
  get "static_pages/hfsk_heat_at_home"
  
  resources :charges
  
  
  get  '/pay_deposit/:id', to: 'charges#new',      as: :show_pay
  post '/pay_deposit/:id', to: 'charges#create',   as: :pay_deposit

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:function_room_enquiry, :hfsk_pay_deposit, :hfsk_find_my_booking, :hfsk_heat_at_home, :new_booking_enquiry, :hfsk_location, :hfsk_gift_vouchers, :hfsk_menu, :hfsk_what_we_do, :hfsk_get_in_touch]
 
  def home
  end
  
  def help
  end
  
  def hfsk_deposit_terms
  end
  
  def hfsk_pay_deposit
    @error = params["error"]   
       @bookings =[]   
      #take params from search on view, note need all params to make use of search code on booking.rb even though some are hidden, or if no search, 
      #send to model to apply SEARCH function, which retrieves matching records and requests only CONFIRMED records
       if params[:booking]
       
         @bookings = Booking.all_search(params[:booking])
               if @bookings.any?
                 params[:booking]= []
                 @bookings = @bookings.sort_by { |hsh| hsh[:booking_date_time] }
               else
                 params[:booking]= []
                 @bookings = 0
               end
       else
          @bookings = []
      
         params[:booking]= []
       end
  end
  
  def hfsk_confirm_deposit
         @booking = Booking.find(params["id"])
  end
  
  def hfsk_find_my_booking
    @error = params["error"]   
       @bookings =[]   
      #take params from search on view, note need all params to make use of search code on booking.rb even though some are hidden, or if no search, 
      #send to Booking.rb model to apply SEARCH function, which retrieves all matching records, any status, past and present
  
   Rails.logger.debug("xxxxx_PARAMS : #{params.inspect}")
    Rails.logger.debug("xxxxx_PARAMS : #{params[:booking].inspect}")
 # Rails.logger.debug("xxxxx_PARAMS : #{params[:booking][:phone].inspect}")

  if params[:booking].present? 
 
  unless params[:booking][:phone].length == 0 || params[:booking][:phone].length >9
     redirect_to hfsk_find_my_booking_path(@bookings), :flash => { :warning => "Please enter a phone number of at least 10 digits"}
  end
  
       
       #if params[:name].present? || params[:email].present?
         
         @bookings = Booking.all_search(params[:booking])
               if @bookings.any?
                 params[:booking]= []
                 @bookings_filtered =[]   
                # code to remove any past bookings
                 @bookings.each do |booking|
                   if (booking.booking_date_time > Date.today.end_of_day)
                     @bookings_filtered << booking
                   end
                   @bookings = @bookings_filtered
                 end
                 @bookings = @bookings.sort_by { |hsh| hsh[:booking_date_time] }
               else
                 params[:booking]= []
                 @bookings = 0
               end
       else
          @bookings = []
      
         params[:booking]= []
       end
  end
  
  def day_picker
  end
  
  def booking_confirm
    @booking = params[:booking]
  end
  
  def booking_enquiry
  end
  
  def booking_advanced
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @bookings = Booking.where("booking_date_time BETWEEN ? AND ?", @date.beginning_of_month.beginning_of_day, @date.end_of_month.end_of_day).where(:status => "Confirmed")
    @bookings_by_date = @bookings.group_by {|i| i.booking_date_time.to_date}     
  end
  
  #testing for new availability
  def new_booking_enquiry
  #  @date = params[:date] ? Date.parse(params[:date]) : Date.today
  #  @bookings = Booking.where("booking_date_time BETWEEN ? AND ?", @date.beginning_of_month.beginning_of_day, @date.end_of_month.end_of_day).where(:status => "Confirmed")
  #  @bookings_by_date = @bookings.group_by {|i| i.booking_date_time.to_date}     
  end
  
  def function_room_enquiry
      if @function 
      else @function = Function.new
      end
  end
  
  def hfsk_home
  end
  
  def hfsk_about
  end
  
  def hfsk_menu
  end
  
  def hfsk_location
  end
  
  def hfsk_gift_vouchers
  end
  
  def hfsk_careers
  end
  
  def hfsk_get_in_touch
      @message = Message.new
      @customer = Customer.new
  end
  
  def hfsk_get_in_touch
    unless @message
      @message = Message.new
    end
  end
  
  def download_menu_pdf
    send_file(
      "#{Rails.root}/public/HF_MENU_SAMPLE_1119.pdf",
      filename: "HF_MENU_SAMPLE_1119.pdf",
      type: "application/pdf"
    )
  end
  
  def download_festive_pdf
    send_file(
      "#{Rails.root}/public/HF_FESTIVE_MENU.pdf",
      filename: "HF_FESTIVE_MENU.pdf",
      type: "application/pdf"
    )
  end
  
  def download_function_pdf
    send_file(
      "#{Rails.root}/public/HF_ENGINE_ROOM_MENU_2016.pdf",
      filename: "HF_ENGINE_ROOM_MENU_2016.pdf",
      type: "application/pdf"
    )
  end
  
  def download_engine_tandc_pdf
    send_file(
      "#{Rails.root}/public/HF_ENGINE_ROOM_HIRE_T&Cs.pdf",
      filename: "HF_ENGINE_ROOM_HIRE_T&Cs.pdf",
      type: "application/pdf"
    )
  end
  
 def send_customer_booking_mail(booking)
     Rails.logger.debug("171_booking : #{booking.inspect}")
    @booking = booking
     Rails.logger.debug("171_booking : #{@booking.inspect}")
      Booking_Mailer.send_customer_booking_mail(@booking).deliver
    redirect_to hfsk_find_my_booking_path, :flash => { :success => "Your booking details have been sent to the email address on the booking."}
  end

end

app/views/static_pages/_side_welcome_news.html.erb
<!-- Instructions: This is the welcome section. -->  

  <div class="row">
    <div class="col-md-4">
    <center><%= image_tag "HF_SK_NEW LOGO_white.png", :class => "photo_img" %></center>
    <br>
     <h6><strong><center><i> BBC FOOD AWARD WINNING BBQ </i></center></strong></h6>
     <hr>
<!-- Instructions: This is the tv section. -->  
         <h6><font color=#D3D3D3><i>Coming Soon...</i></font><br></h6>
         <h5><b><center>Sam and Shauna's Big Cookout</b></h5>
         <h6><small><center>Starts April 9th, 2018 on the BBC</small></center></h6>
        <center> <%= image_tag("TV_BIG_COOK_OUT.jpg", size: "310x200") %></center>

<!-- Instructions: This is the current news item section. -->  
        <hr>
       <center> <%= image_tag("book_cover_t.png", size: "180x240") %></center>
       <hr>
        
<!-- Instructions: This is the amazon buy section. -->  

        <h6><center>Our cook book is available to buy in our restaurant and from Amazon...</center></h6>
        <center><%= link_to image_tag("amazon_index.png", size: "150x30"), "http://www.amazon.co.uk/Hangfire-Cookbook-Recipes-Adventures-American-y/dp/1849497656/ref=sr_1_1?s=books&ie=UTF8&qid=1452690652&sr=1-1&keywords=hang+fire+smokehouse", :target => "_blank" %>
        </center>
        </h6>
       </div>
   
       

app/views/static_pages/booking_enquiry.html.erb
<%= render 'layouts/external_header' %>
   
<%= render 'static_pages/side_welcome_open_hours'%>

<!-- Instructions: This is the menu section. -->  

   <div class="col-md-6" style="padding-top:10px;">
   
    <h5><b><font color=#9ACD32>PLEASE NOTE</font></b></h5>
    <h4>To use our new, improved booking system!<br>
    <%= link_to "CLICK HERE", new_booking_enquiry_path, :style => "color:#FFC300" %></h4>
    <br><br>
    <h6><small>THIS PAGE IS NOT LONGER IN USE,<br>PLEASE UPDATE YOUR BOOKMARK TO THE NEW BOOKING SITE.</small></h6>
    
        </div>
        </div>




 
 
   
   

app/views/static_pages/hfsk_blog.html.erb
<%= render 'layouts/external_header' %>
<%= render 'static_pages/side_welcome_news' %>
   
   
<!-- Instructions: This is the blog section. -->  

 <div class="col-md-8">
 <h4><i class="fa fa-newspaper-o fa-fw"></i><strong>  BLOG</strong> </h4>
  
 <h5>Keep up with the latest news on our blog:<br><br><u> <%= link_to "Click here for Hang Fire blog", "http://hangfiresmokehouse.com", class: 'ex_head_link', :target => "_blank"%></u></h5>
  
 </div>

app/views/static_pages/hfsk_careers.erb
 <%= render 'layouts/external_header' %>

<%= render 'static_pages/side_welcome_news'%>

 
<!-- Instructions: This is the careers section. -->  
 

  <div class="col-md-8">
	  <h4><b>Careers at Hang Fire</b></h4><br>
  </div>
   
   <div class="col-md-3">
	    <%= image_tag "HJ-Hangfire-3950.jpg", :class => "photo_img4" %>
   </div>
   <div class="col-md-4">
	  <h6><small>At Hang Fire, our values are underpinned by the need to put our customers first. Great customer service is the driving force behind every great restaurant, making it an essential requirement if you'd like to work for us. We are looking for passionate, dynamic and hard working people to join our team. If you want a fast-paced, hands-on career, Hang Fire is just the place for you.</small></h6>
	  </div>
	  
	<div class="col-md-3">
	<h6><small>
	  Current open positions:<br>
	  <br>
1. Assistant Manager (Full Time)<br>
2. Bar Tender (Full Time)<br>
3. Waitress / Waiter (Full Time)<br>
4. Waitress / Waiter (Part Time)<br>
5. Kitchen Porter (Part Time)<br>
</small></h6>
 
     </div>
   <div class="col-md-3"><br>
	    <%= image_tag "HJ-Hangfire-5141.jpg", :class => "photo_img4" %>
  </div>
    <div class="col-md-8">
  <h6><small>
	  For more information drop us an email:</small> <b>hangfirebarry@gmail.com</b>
	  </h6>
  </div>

   
 
 

app/views/static_pages/hfsk_find_my_booking.html.erb
<div class="hfsk-location-background">

<%= render 'layouts/external_header' %>
<div class="row">
 <div class="col-md-10 col-md-offset-1  "> 
 <div class="row">
  <div class="col-md-4">
  </div>
 
<!-- Instructions: This is the intro section. -->  


  <div class="col-md-6">
  <h5>FIND MY BOOKING(S) </h5>
  <br>
  
  
  <h6>If you have lost the details of a future booking, you can retrieve it here:</h6>
  <br>
    
  <!-- Instructions: This is the search section. -->     
    <div class="well well-sm">
     <%= form_tag hfsk_find_my_booking_path, method: :get, :class => "form-inline" do %>

         <h6>Please enter telephone or email given when booking was made:<br><br>
         <%= hidden_field(:booking, :name, :placeholder => "Name", :class=>"form-control input-sm") %>
         <%= hidden_field(:booking, :booking_date_time, :placeholder => "DateTime", :class=>"form-control input-sm") %>
 
         <%= text_field(:booking, :phone, :placeholder => "Phone", :class=>"form-control input-sm") %>
         or
         <%= text_field(:booking, :email, :placeholder => "Email", :class=>"form-control input-sm") %>
    
       <br><br>
       <button type="submit" class="btn btn-primary btn-sm">Search</button>
     <% end %>
     </div>
    
<!-- Instructions: This is no bookings found section. -->  
     
       <% if @bookings==0 || !@bookings.any? %>
	   
	    <h5>No bookings found for that input. Please try with any other information you have, <br>
			else <%= link_to "GET IN TOUCH", hfsk_get_in_touch_path, style: 'color:#d3d3d3;' %> and one of our staff will assist you.</h5>

<!-- Instructions: This is the bookings found section. -->  	
		   
	   <% elsif @bookings.any? %>
     
     <TABLE class="table table-bordered table-condensed ">
       <thead>
         <tr>
           
           <th><center><small>When</center></th>
           <th><small>Status</th>
           <th><small>Customer</th>
           <th><center><small>Diners</center></th>
           <th><center><small>Deposit Due</center></th>
           <th><center><small>Deposit Paid</center></th>
           <th><small>Date Booked</th>
		   <th><small>Send Email<br> Reminder</th>
           </tr>
         </thead>
         <tbody>

         <% @bookings.each do |booking| %>
    <% if booking.status == "Cancelled" %>
      <tr class="danger">
         <% elsif ["Paid in Full", "No Deposit Required"].include? Booking.deposit_amount(booking).first  %>
      <tr class="success">
         <% else %>
      <tr class="default">
    <% end %>
         
        
         <td><small><center><%= booking.booking_date_time.strftime('%A') %>, <%= booking.booking_date_time.strftime('%H:%M') %><br>
         <%= booking.booking_date_time.strftime('%d %b %y') %></center></td>
         <td> <small><%= booking.status %></td>
         <td><strong><%= booking.name %></strong><br></td>
         <td><small><center><%= booking.number_of_diners %></center></td>
         <% if booking.number_of_diners >= Rdetail.deposit_table_size %>
           <td><small><center>£<%= number_with_precision((booking.number_of_diners*10), :precision => 2) %></center></td>
         <% else %>
           <td><small><center>£0</center></td>
         <% end %>
        
         <td><small><center><% if booking.deposit_amount? %>£<%= number_with_precision(booking.deposit_amount, :precision => 2) %></center><% end %></td>
         
         <td><small><i><%= booking.created_at.strftime('%d %b %Y') %></small></td>
         
	     <td><% if booking.status =="Confirmed" %> <button type="button" class="btn btn-warning btn-sm"><%= link_to 'Send email', send_customer_booking_mail_path(booking) %> </button>
			 <% else %><% end %></td>
       </tr>
    <% end %>  
   
  </tbody>
</table>
<br>

    <% end %>  
     <br><br><br><br><br>
  </div> 
   </div> 
    </div>

   
 
 

app/views/static_pages/hfsk_pay_deposit.html.erb
<div class="hfsk-location-background">

<%= render 'layouts/external_header' %>
<div class="row">
 <div class="col-md-10 col-md-offset-1  "> 
 <div class="row">
  <div class="col-md-4">
  </div>
 
<!-- Instructions: This is the intro section. -->  


  <div class="col-md-8">
  <h5>PAY YOUR DEPOSIT - <small>for tables of <%= Rdetail.deposit_table_size %> or more </small></h5>
  <br>
  
  
  <h6>You can now pay your deposit securely via credit/debit card, by following these steps:</h6>
    
    <% if @error.present? %>
      <!-- Instructions: This is the error section. -->    
      <h4>
      <ol>
      <li>Search for your booking.</li>
        <li>Review details and confirm deposit amount.</li>
        <li>Pay your deposit using Stripe secure card payment.</li>
        <li>Receive your payment confirmation details and email.</li>
        or
        <font color="#FFFF00">  <li>Receive error messages and instructions.</li></font>
      </ol>
      </h4>
      <br><hr>
      
      <% if @error %>
      <h6><small>Stripe System Error: <%= @error %></h6>
      <% end %>
      
      <h6>We're sorry, there has been a problem with your card<br> 
      and Stripe has not accepted payment at this time.<br>
      <br><b>
      Your card has not been charged.
      <br><br></b>
      Please contact us by email at contacthangfirebbq@gmail.com to pay your deposit.</h6>
    
   <!-- Instructions: This is the processing section. -->  
   <% elsif @bookings==0 || !@bookings.any? %>
 
     <h4>
     <ol>
      <font color="#FFFF00"> 
       <li>Please read the deposit terms and conditions carefully.</li>
       <li>Search for your booking.</li></font>
       <li>Review details and confirm deposit amount.</li>
       <li>Pay your deposit using Stripe secure card payment.</li>
       <li>Receive your payment confirmation details and email.</li>
     </ol>
     </h4>
     <br>
     
  <!-- Instructions: This is the search section. -->     
    <div class="well well-sm">
     <%= form_tag hfsk_pay_deposit_path, method: :get, :class => "form-inline" do %>

         <h6>Please enter telephone or email given when booking was made:<br><br>
         <%= hidden_field(:booking, :name, :placeholder => "Name", :class=>"form-control input-sm") %>
         <%= hidden_field(:booking, :booking_date_time, :placeholder => "DateTime", :class=>"form-control input-sm") %>
 
         <%= text_field(:booking, :phone, :placeholder => "Phone", :class=>"form-control input-sm") %>
         or
         <%= text_field(:booking, :email, :placeholder => "Email", :class=>"form-control input-sm") %>
    
       <br><br>
       <button type="submit" class="btn btn-primary btn-sm">Search</button>
     <% end %>
     </div>
  
      <hr>
      <!-- Instructions: This is the search section. -->   
     <h6>DEPOSIT TERMS and CONDITIONS</h6>
     <h6><ul>
       <li>A deposit is required for tables of <%= Rdetail.deposit_table_size %> or more.</li> 
       <li>The deposit is £10 per person (which includes children).</li>
       <li>The full amount will be deducted from your bill at the end of your meal.</li>
       <li>If your numbers change, and you let us know in advance, you won't lose any of your deposit.</li>
       <li>You will be entitled to a full refund of your deposit anytime up until 3 days (72 hours) before your reservation.</li>   
    </h6>
      <br><br><br><br><br>
     
     <% else @bookings.any? %>
<!-- Instructions: This is the review and pay section. -->  
     
      <h4>
      <ol>
       <li>Search for your booking.</li>
        <font color="#FFFF00">  <li>Review details and confirm deposit amount.</li> </font>
         <font color="#FFFF00"><li>Pay your deposit using Stripe secure card payment.</li> </font>
        <li>Receive your payment confirmation details and email.</li>
      </ol>
      </h4>
      <br>
     
     <TABLE class="table table-bordered table-condensed ">
       <thead>
         <tr>
           <th colspan="1"><center><small>Action</th>
           <th><center><small>When</center></th>
           <th><small>Status</th>
           <th><small>Customer</th>
           <th><center><small>Diners</center></th>
           <th><center><small>Deposit Due</center></th>
           <th><center><small>Deposit Paid</center></th>
           <th><small>Date Booked</th>
           </tr>
         </thead>
         <tbody>

         <% @bookings.each do |booking| %>
    <% if booking.status == "Cancelled" %>
      <tr class="danger">
         <% elsif ["Paid in Full", "No Deposit Required"].include? Booking.deposit_amount(booking).first  %>
      <tr class="success">
         <% else %>
      <tr class="default">
    <% end %>
         
         <td width="20%">  <% unless booking.status == "Cancelled" %>
         <small><center><%= Booking.deposit_amount(booking).first %>
             
                 <% if Booking.deposit_amount(booking).second.to_i> 0 %>
                     : £<%= Booking.deposit_amount(booking).second.to_i %>
                   
                   <%= form_tag pay_deposit_path(booking) do %>
                     <script src="https://checkout.stripe.com/v2/checkout.js"
                       class="stripe-button"
                       data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                       data-name="Hang Fire Southern Kitchen"
                       data-description="Deposit"
                       data-email=<%= booking.email%>
                       data-amount="<%= (Booking.deposit_amount(booking).second*100) %>"
                       data-currency="GBP"
                       data-allow-remember-me=false
                       data-locale="auto">
                       </script>
                   <% end %>
                   <% else %>
                  
             <% end %>
          <% end %>
         </td>
         <td><small><center><%= booking.booking_date_time.strftime('%A') %>, <%= booking.booking_date_time.strftime('%H:%M') %><br>
         <%= booking.booking_date_time.strftime('%d %b %y') %></center></td>
         <td> <small><%= booking.status %></td>
         <td><strong><%= booking.name %></strong><br>
         <small><i><%= booking.phone %>, <%= booking.email %></small></td>
         <td><small><center><%= booking.number_of_diners %></center></td>
         <% if booking.number_of_diners >= Rdetail.deposit_table_size %>
           <td><small><center>£<%= number_with_precision((booking.number_of_diners*10), :precision => 2) %></center></td>
         <% else %>
           <td><small><center>£0</center></td>
         <% end %>
        
         <td><small><center><% if booking.deposit_amount? %>£<%= number_with_precision(booking.deposit_amount, :precision => 2) %></center><% end %></td>
         <td><small><i><%= booking.created_at.strftime('%d %b %Y') %></small></td>
       </tr>
    <% end %>  
   
  </tbody>
</table>
<br>

<% end %>
     <br><br><br><br><br>
  </div> 
   </div> 
    </div>

   
 
 