config/routes.rb
Rails.application.routes.draw do
 resources :troncs
 match 'staffhours/all/edit' => 'staffhours#edit_all', :as => :edit_all, :via => :get
 match 'staffhours/all/edit_last' => 'staffhours#edit_last', :as => :edit_last, :via => :get
 match 'staffhours/all/edit_next' => 'staffhours#edit_next', :as => :edit_next, :via => :get
 match 'staffhours/all' => 'staffhours#update_all', :as => :update_all, :via => :put
 match 'staffhours/show_team' => 'staffhours#show_team', :as => :show_team, :via => :get
 match 'staffhours/accrued_vacation' => 'staffhours#accrued_vacation', :as => :accrued_vacation, :via => :get

 resources :staffhours
 resources :accruel_rates
  resources :staffs do
    resources :staffevents
  end  
  resources :expenses do
      collection { get :show_many };
      collection { get :add_new }
    end
  resources :dailystats
  resources :dailybanks do
    member do
       post 'submit_comment';
       post 'mgmt_lock';
       post 'lock_float';
       post 'lock_event';
       post 'create_new_expense_record';
       post 'put_to_mgmt_review';
       post 'no_expenses_to_add';
       post 'mgmt_recalculate'; 
       get 'mgmt_review';
    end
     resources :expenses
  end
 
  resources :exemptions
  resources :functions
  resources :cashfloats do
      collection { post :validate };
      collection { get :show_float }
    end

  get 'daily_checks/today'
  get 'daily_checks/yesterday'
  get 'daily_checks/history'

  get 'messages/new'
  post 'messages/create'   => 'messages#create'
  post 'customers/subscribe'   => 'customers#subscribe'

  resources :errors
  resources :users
  resources :customers
  resources :bookings do
      collection { post :booking_confirmation };
      collection { post :booking_cancellation };
      collection { post :booking_get_times };
      collection { post :booking_advanced };
      collection { post :mgmt_edit };
    end  
  resources :tables do
      collection { post :booking_enquiry }
    end  
  resources :rdetails
  resources :restaurants
  resources :accounts
  resources :enquiries
  resources :categories
  resources :products do
    		 collection { post :import }
       end
   resources :sessions, only: [:new, :create, :destroy]
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

  root 'static_pages#hfsk_home'
 
 
 
  get '/index_full' => 'dailybanks#index_full'
  get '/index_ongoing' => 'dailybanks#index_ongoing'
  get '/latest' => 'dailybanks#latest'
  get '/history' => 'dailybanks#history'
  get '/history_week' => 'dailybanks#history_week'
  get '/history_month' => 'dailybanks#history_month'
  get '/tax_quarter' => 'dailybanks#tax_quarter'
  get '/card_tips_report' => 'dailybanks#card_tips_report'
  get '/home' => 'static_pages#home'
  get '/heat_at_home' => 'static_pages#hfsk_heat_at_home'
  get '/help' => 'static_pages#help'
  get '/booking_enquiry' => 'static_pages#booking_enquiry'
  get '/new_booking_enquiry' => 'static_pages#new_booking_enquiry'
  get '/booking_advanced' => 'static_pages#booking_advanced'
  get '/function_room_enquiry' => 'static_pages#function_room_enquiry'
  get '/download_menu_pdf' => 'static_pages#download_menu_pdf'
  get '/download_function_pdf' => 'static_pages#download_function_pdf'
  get '/download_engine_tandc_pdf' => 'static_pages#download_engine_tandc_pdf'
  get '/download_festive_pdf' => 'static_pages#download_festive_pdf'
  get '/basic_report' => 'bookings#basic_report'
  get '/deposit_report' => 'bookings#deposit_report'
  get '/confirmation_report' => 'bookings#confirmation_report'
  get '/confirmation_report_month' => 'bookings#confirmation_report_month'
  get '/day_to_view_bookings_report' => 'bookings#day_to_view_bookings_report'
  get '/calendar' => 'bookings#calendar'
  get '/availability' => 'bookings#availability'
  get '/availability_detail' => 'bookings#availability_detail'
  get '/all_customers' => 'customers#all_customers'
  get '/all_bookings' => 'bookings#all_bookings'
  get '/download_bookings_pdf' => "bookings#download_bookings_pdf"
  get '/download_bookings_evening_pdf' => "bookings#download_bookings_evening_pdf"
  get '/mgmt_edit_booking' => 'bookings#mgmt_edit'
  get '/search_bookings' => 'bookings#search_bookings' 
  get '/cashfloats_validate' => 'cashfloats#validate'  
  get '/download_end_of_night_pdf' => "dailybanks#download_end_of_night_pdf" 
  get '/download_dailybank_tax_accounting_pdf' => "dailybanks#download_dailybank_tax_accounting_pdf"
  get '/download_card_tips_report_pdf' => "dailybanks#download_card_tips_report_pdf" 
  get '/download_expenses_report_pdf' => "expenses#download_expenses_report_pdf" 
  get '/download_tronc_allocation_report_pdf' => "staffhours#download_tronc_allocation_report_pdf" 
  get '/download_vacation_accruel_report_pdf' => "staffhours#download_vacation_accruel_report_pdf" 
  
  
  get '/hfsk_home' => 'static_pages#hfsk_home'
  get '/hfsk_about' => 'static_pages#hfsk_about'
  get '/hfsk_blog' => 'static_pages#hfsk_blog'
  get '/hfsk_booking' => 'static_pages#booking_enquiry'
  get '/hfsk_location' => 'static_pages#hfsk_location'
  get '/hfsk_pay_deposit' => 'static_pages#hfsk_pay_deposit'
  get '/hfsk_deposit_terms' => 'static_pages#hfsk_deposit_terms'
  get '/hfsk_confirm_deposit' => 'static_pages#hfsk_confirm_deposit'
  get '/hfsk_get_in_touch' => 'static_pages#hfsk_get_in_touch'
  get '/hfsk_careers' => 'static_pages#hfsk_careers'
  get '/hfsk_menu' => 'static_pages#hfsk_menu'
  get '/hfsk_holiday_season' => 'static_pages#hfsk_holiday_season'
  get '/hfsk_gift_vouchers' => 'static_pages#hfsk_gift_vouchers'
  get '/hfsk_find_my_booking' => 'static_pages#hfsk_find_my_booking'
  get '/hfsk_heat_at_home' => 'static_pages#hfsk_heat_at_home'
  
  get '/hfsk_home_new' => 'static_pages#hfsk_home_new'
  get '/new_booking_enquiry_new' => 'static_pages#new_booking_enquiry_new'
  get '/hfsk_location_new' => 'static_pages#hfsk_location_new'
  get '/hfsk_menu_new' => 'static_pages#hfsk_menu_new'
  get '/hfsk_what_we_do' => 'static_pages#hfsk_what_we_do'
  get '/hfsk_get_in_touch_new' => 'static_pages#hfsk_get_in_touch_new'
  get '/hfsk_heat_at_home' => 'static_pages#hfsk_heat_at_home'
 
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/day_picker"
  get "static_pages/booking_enquiry"
  get "static_pages/new_booking_enquiry"
  get "static_pages/booking_advanced"
  get "static_pages/function_room_enquiry"
  get "static_pages/booking_confirm"  
  
  get "static_pages/hfsk_home"
  get "static_pages/hfsk_blog"
  get "static_pages/hfsk_about"
  get "static_pages/hfsk_location"
  get "static_pages/hfsk_pay_deposit"
  get "static_pages/hfsk_deposit_terms"
  get "static_pages/hfsk_confirm_deposit"
  get "static_pages/hfsk_get_in_touch"
  get "static_pages/hfsk_careers"
  get "static_pages/hfsk_menu"
  get "static_pages/hfsk_holiday_season"
  get "sessions/new"
  get "static_pages/new_booking_enquiry_new"
  get "send_customer_booking_mail", to: 'static_pages#send_customer_booking_mail', as: :send_customer_booking_mail
  get "static_pages/hfsk_heat_at_home"
  
  resources :charges
  
  
  get  '/pay_deposit/:id', to: 'charges#new',      as: :show_pay
  post '/pay_deposit/:id', to: 'charges#create',   as: :pay_deposit

end

app/models/tronc.rb
class Tronc < ActiveRecord::Base
  
  validates :end_date, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  
  validates :foh_split, presence: true
  validates :kitchen_split, presence: true
  validates :card_split, presence: true
  validates :mgr_split, presence: true
  validates :foh_method, presence: true
  validates :kit_method, presence: true
  
  validate :split_must_equal_100
  validates_uniqueness_of :start_date, :scope => [:end_date, :end_date]
  
  TRONC_STATUS_TYPES = ["Current", "Complete"]
  TRONC_METHOD_TYPES = ["By Hours", "Even Split"]
  
  def split_must_equal_100
    unless (self.kitchen_split + self.foh_split + self.card_split + self.mgr_split) ==100
       errors.add(:kitchen_split, ":  Card%, Mgr%, FOH%, Kitchen% must add up to 100 ")
  end
end
end

app/controllers/troncs_controller.rb
class TroncsController < ApplicationController
  before_action :set_tronc, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy, :index, :new]
  
  # GET /troncs
  # GET /troncs.json
  def index
    @troncs = Tronc.all
    @troncs = @troncs.sort_by { |hsh| hsh[:start_date] }.reverse
  end

  # GET /troncs/1
  # GET /troncs/1.json
  def show
  end

  # GET /troncs/new
  def new
    @tronc = Tronc.new
  end

  # GET /troncs/1/edit
  def edit
  end

  # POST /troncs
  # POST /troncs.json
  def create
    @tronc = Tronc.new(tronc_params)

    respond_to do |format|
      if @tronc.save
        format.html { redirect_to @tronc, notice: 'Tronc was successfully created.' }
        format.json { render :show, status: :created, location: @tronc }
      else
        format.html { render :new }
        format.json { render json: @tronc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /troncs/1
  # PATCH/PUT /troncs/1.json
  def update
    respond_to do |format|
      if @tronc.update(tronc_params)
        format.html { redirect_to @tronc, notice: 'Tronc was successfully updated.' }
        format.json { render :show, status: :ok, location: @tronc }
      else
        format.html { render :edit }
        format.json { render json: @tronc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /troncs/1
  # DELETE /troncs/1.json
  def destroy
    @tronc.destroy
    respond_to do |format|
      format.html { redirect_to troncs_url, notice: 'Tronc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tronc
      @tronc = Tronc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tronc_params
      params.require(:tronc).permit(:start_date, :end_date, :status, :total, :kitchen_split, :foh_split, :card_split, :mgr_split, :foh_method, :kit_method)
    end
end

app/helpers/troncs_helper.rb
module TroncsHelper
end

app/views/troncs/_form.html.erb
<%= bootstrap_form_for(@tronc) do |f| %>
  <% if @tronc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tronc.errors.count, "error") %> prohibited this tronc from being saved:</h2>

      <ul>
      <% @tronc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="col-md-4">
    <%= f.select(:status, Tronc::TRONC_STATUS_TYPES, :label => "Status?") %>
    <%= f.date_select :start_date %>
    <hr>
    <%= f.text_field :card_split, label: "Card Processing %" %>
        <hr>
    <%= f.text_field :foh_split, label: "Front of House %" %>
    <%= f.select(:foh_method, Tronc::TRONC_METHOD_TYPES, :label => "FOH Split Method?") %>
</div>
 <div class="col-md-4">
   <%= f.text_field :total, :disabled => true %>
   <%= f.date_select :end_date %>
       <hr>
    <%= f.text_field :mgr_split, label: "Managers %"  %>
        <hr>
    <%= f.text_field :kitchen_split, label: "Kitchen %"  %>
    <%= f.select(:kit_method, Tronc::TRONC_METHOD_TYPES, :label => "Kitchen Split Method?") %>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/troncs/edit.html.erb
<div class="row">
<div class="col-md-2">
<%= render 'layouts/sidebar' %>
</div>

<div class="col-md-10">
<h3>Edit TRONC Period</h3><br>
<br>

<%= render 'form' %>

<%= link_to 'Show', @tronc %> |
<%= link_to 'Back', troncs_path %>
</div>

app/views/troncs/index.html.erb
<div class="row">
<div class="col-md-2">
<%= render 'layouts/sidebar' %>
</div>

<div class="col-md-8">

<h2>TRONC Periods</h2>
<br>

<table class="table">
  <thead>
    <tr>
       <th>Status</th>
       <th>Start date</th>
       <th>End date</th>
       <th style="text-align:right">Card %</th>
       <th style="text-align:right">Mgrs %</th>
       <th style="text-align:right">FOH %</th>
       <th style="text-align:right">Kitchen %</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @troncs.each do |tronc| %>
      <tr>
        <td><%= tronc.status %></td>
        <td><%= tronc.start_date.strftime('%d %B %Y') %></td>
        <td><%= tronc.end_date.strftime('%d %B %Y') %></td>
        <td style="text-align:right"><%= number_with_precision(tronc.card_split, :precision => 2)  %> </td>
        <td style="text-align:right"><%= number_with_precision(tronc.mgr_split, :precision => 2)  %> </td>
        <td style="text-align:right"><%= number_with_precision(tronc.foh_split, :precision => 2)  %><br><%= tronc.foh_method %></td>
        <td style="text-align:right"><%= number_with_precision(tronc.kitchen_split, :precision => 2)  %><br><%= tronc.kit_method %> </td>
        <td><%= link_to 'Show', tronc %></td>
        <td><%= link_to 'Edit', edit_tronc_path(tronc) %></td>
        <td><%= link_to 'Destroy', tronc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Tronc Period', new_tronc_path, style: 'color:#d3d3d3'  %>

app/views/troncs/new.html.erb
<div class="row">
<div class="col-md-2">
<%= render 'layouts/sidebar' %>
</div>

<div class="col-md-10">
<h3>New Tronc Period</h3><br>

<%= render 'form' %>

<%= link_to 'Back', troncs_path, style: 'color:#d3d3d3' %>

app/views/troncs/show.html.erb
<div class="row">
<div class="col-md-2">
<%= render 'layouts/sidebar' %>
</div>

<div class="col-md-4">
<h3>TRONC Period</h3><br>
<br>


<p>
  <strong>Status:</strong>
  <%= @tronc.status %>
</p>

<p>
  <strong>Period:</strong>
  <%= @tronc.start_date.strftime('%d %B %Y')  %> -  <%= @tronc.end_date.strftime('%d %B %Y')  %>
</p>

<br>
<h6>Splits</h6>
<p>
  <strong>Card Processing:</strong>
  <%= @tronc.card_split %>%
</p>
<p>
  <strong>Managers</strong>
  <%= @tronc.mgr_split %>%
</p>
<p>
  <strong>Front of House:</strong>
  <%= @tronc.foh_split %>%,  <i><%= @tronc.foh_method %></i>
</p>
<p>
  <strong>Kitchen:</strong>
  <%= @tronc.kitchen_split %>%, <i> <%= @tronc.kit_method %></i>
</p>
<br>
<h6>TRONC Total: </h6>
<p>
  <%= @tronc.total %>
</p>

<%= link_to 'Edit', edit_tronc_path(@tronc) %> |
<%= link_to 'Show ALl', troncs_path %>