config/routes.rb
Rails.application.routes.draw do
 resources :troncs
 match 'staffhours/all/edit' => 'staffhours#edit_all', :as => :edit_all, :via => :get
 match 'staffhours/all/edit_last' => 'staffhours#edit_last', :as => :edit_last, :via => :get
 match 'staffhours/all/edit_next' => 'staffhours#edit_next', :as => :edit_next, :via => :get
 match 'staffhours/all' => 'staffhours#update_all', :as => :update_all, :via => :put
 match 'staffhours/show_team' => 'staffhours#show_team', :as => :show_team, :via => :get
 match 'staffhours/accrued_vacation' => 'staffhours#accrued_vacation', :as => :accrued_vacation, :via => :get

 resources :staffhours
 resources :accruel_rates
  resources :staffs do
    resources :staffevents
  end  
  resources :expenses do
      collection { get :show_many };
      collection { get :add_new }
    end
  resources :dailystats
  resources :dailybanks do
    member do
       post 'submit_comment';
       post 'mgmt_lock';
       post 'lock_float';
       post 'lock_event';
       post 'create_new_expense_record';
       post 'put_to_mgmt_review';
       post 'no_expenses_to_add';
       post 'mgmt_recalculate'; 
       get 'mgmt_review';
    end
     resources :expenses
  end
 
  resources :exemptions
  resources :functions
  resources :cashfloats do
      collection { post :validate };
      collection { get :show_float }
    end

  get 'daily_checks/today'
  get 'daily_checks/yesterday'
  get 'daily_checks/history'

  get 'messages/new'
  post 'messages/create'   => 'messages#create'
  post 'customers/subscribe'   => 'customers#subscribe'

  resources :errors
  resources :users
  resources :customers
  resources :bookings do
      collection { post :booking_confirmation };
      collection { post :booking_cancellation };
      collection { post :booking_get_times };
      collection { post :booking_advanced };
      collection { post :mgmt_edit };
    end  
  resources :tables do
      collection { post :booking_enquiry }
    end  
  resources :rdetails
  resources :restaurants
  resources :accounts
  resources :enquiries
  resources :categories
  resources :products do
    		 collection { post :import }
       end
   resources :sessions, only: [:new, :create, :destroy]
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

  root 'static_pages#hfsk_home'
 
 
 
  get '/index_full' => 'dailybanks#index_full'
  get '/index_ongoing' => 'dailybanks#index_ongoing'
  get '/latest' => 'dailybanks#latest'
  get '/history' => 'dailybanks#history'
  get '/history_week' => 'dailybanks#history_week'
  get '/history_month' => 'dailybanks#history_month'
  get '/tax_quarter' => 'dailybanks#tax_quarter'
  get '/card_tips_report' => 'dailybanks#card_tips_report'
  get '/home' => 'static_pages#home'
  get '/heat_at_home' => 'static_pages#hfsk_heat_at_home'
  get '/help' => 'static_pages#help'
  get '/booking_enquiry' => 'static_pages#booking_enquiry'
  get '/new_booking_enquiry' => 'static_pages#new_booking_enquiry'
  get '/booking_advanced' => 'static_pages#booking_advanced'
  get '/function_room_enquiry' => 'static_pages#function_room_enquiry'
  get '/download_menu_pdf' => 'static_pages#download_menu_pdf'
  get '/download_function_pdf' => 'static_pages#download_function_pdf'
  get '/download_engine_tandc_pdf' => 'static_pages#download_engine_tandc_pdf'
  get '/download_festive_pdf' => 'static_pages#download_festive_pdf'
  get '/basic_report' => 'bookings#basic_report'
  get '/deposit_report' => 'bookings#deposit_report'
  get '/confirmation_report' => 'bookings#confirmation_report'
  get '/confirmation_report_month' => 'bookings#confirmation_report_month'
  get '/day_to_view_bookings_report' => 'bookings#day_to_view_bookings_report'
  get '/calendar' => 'bookings#calendar'
  get '/availability' => 'bookings#availability'
  get '/availability_detail' => 'bookings#availability_detail'
  get '/all_customers' => 'customers#all_customers'
  get '/all_bookings' => 'bookings#all_bookings'
  get '/download_bookings_pdf' => "bookings#download_bookings_pdf"
  get '/download_bookings_evening_pdf' => "bookings#download_bookings_evening_pdf"
  get '/mgmt_edit_booking' => 'bookings#mgmt_edit'
  get '/search_bookings' => 'bookings#search_bookings' 
  get '/cashfloats_validate' => 'cashfloats#validate'  
  get '/download_end_of_night_pdf' => "dailybanks#download_end_of_night_pdf" 
  get '/download_dailybank_tax_accounting_pdf' => "dailybanks#download_dailybank_tax_accounting_pdf"
  get '/download_card_tips_report_pdf' => "dailybanks#download_card_tips_report_pdf" 
  get '/download_expenses_report_pdf' => "expenses#download_expenses_report_pdf" 
  get '/download_tronc_allocation_report_pdf' => "staffhours#download_tronc_allocation_report_pdf" 
  get '/download_vacation_accruel_report_pdf' => "staffhours#download_vacation_accruel_report_pdf" 
  
  
  get '/hfsk_home' => 'static_pages#hfsk_home'
  get '/hfsk_about' => 'static_pages#hfsk_about'
  get '/hfsk_blog' => 'static_pages#hfsk_blog'
  get '/hfsk_booking' => 'static_pages#booking_enquiry'
  get '/hfsk_location' => 'static_pages#hfsk_location'
  get '/hfsk_pay_deposit' => 'static_pages#hfsk_pay_deposit'
  get '/hfsk_deposit_terms' => 'static_pages#hfsk_deposit_terms'
  get '/hfsk_confirm_deposit' => 'static_pages#hfsk_confirm_deposit'
  get '/hfsk_get_in_touch' => 'static_pages#hfsk_get_in_touch'
  get '/hfsk_careers' => 'static_pages#hfsk_careers'
  get '/hfsk_menu' => 'static_pages#hfsk_menu'
  get '/hfsk_holiday_season' => 'static_pages#hfsk_holiday_season'
  get '/hfsk_gift_vouchers' => 'static_pages#hfsk_gift_vouchers'
  get '/hfsk_find_my_booking' => 'static_pages#hfsk_find_my_booking'
  get '/hfsk_heat_at_home' => 'static_pages#hfsk_heat_at_home'
  
  get '/hfsk_home_new' => 'static_pages#hfsk_home_new'
  get '/new_booking_enquiry_new' => 'static_pages#new_booking_enquiry_new'
  get '/hfsk_location_new' => 'static_pages#hfsk_location_new'
  get '/hfsk_menu_new' => 'static_pages#hfsk_menu_new'
  get '/hfsk_what_we_do' => 'static_pages#hfsk_what_we_do'
  get '/hfsk_get_in_touch_new' => 'static_pages#hfsk_get_in_touch_new'
  get '/hfsk_heat_at_home' => 'static_pages#hfsk_heat_at_home'
 
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/day_picker"
  get "static_pages/booking_enquiry"
  get "static_pages/new_booking_enquiry"
  get "static_pages/booking_advanced"
  get "static_pages/function_room_enquiry"
  get "static_pages/booking_confirm"  
  
  get "static_pages/hfsk_home"
  get "static_pages/hfsk_blog"
  get "static_pages/hfsk_about"
  get "static_pages/hfsk_location"
  get "static_pages/hfsk_pay_deposit"
  get "static_pages/hfsk_deposit_terms"
  get "static_pages/hfsk_confirm_deposit"
  get "static_pages/hfsk_get_in_touch"
  get "static_pages/hfsk_careers"
  get "static_pages/hfsk_menu"
  get "static_pages/hfsk_holiday_season"
  get "sessions/new"
  get "static_pages/new_booking_enquiry_new"
  get "send_customer_booking_mail", to: 'static_pages#send_customer_booking_mail', as: :send_customer_booking_mail
  get "static_pages/hfsk_heat_at_home"
  
  resources :charges
  
  
  get  '/pay_deposit/:id', to: 'charges#new',      as: :show_pay
  post '/pay_deposit/:id', to: 'charges#create',   as: :pay_deposit

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy, :index]
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = []
     @expenses_by_dailybank = []
      #take params from search on Index view, or if no search, return 0
      #send to model to apply SEARCH function, which retrieves matching records 
       if params[:from]
         @dailybanks = Dailybank.search(params)
               if @dailybanks.any?
                 #AT THIS STAGE DAILYBANK RECORDS ARE SORTED IN DATE ORDER
                 #CHANGED THIS CODE AS DATE ORDERING WAS NOT WORKING
             
              #   @dailybank_ids = @dailybanks.map { |x| x[:id] }
              # params= []
               #  @expenses = Expense.where(:dailybank_id => @dailybank_ids) 
              #  @expenses = Expense.where(:dailybank_id => @dailybanks)
              # @dailybanks.each do |dailybank|
                 #    dailybank[:expenses] =  Expense.where(:dailybank_id => @dailybank_ids) 
                     #  Rails.logger.debug("dailybanks_in_search: AFTER: #{dailybank.inspect}")
                  # end
               #  @expenses_by_dailybank = @expenses.group_by { |t| t.dailybank_id }
               #THIS IS BAD CODE AS JUST REPLACING NAMED VARIABLE WITH OTHER NOT MATCHING VALUE
               #BUT DOING FOR QUICK WORK AROUND SO DONT HAVE TO CHANGE TOO MUCH OF THE INDEX VIEW CODE ALSO
                @expenses_by_dailybank = @dailybanks
                return @expenses_by_dailybank
                else
                 params= []
                 @expenses = 1
               end
       else
         @expenses = 0
         params= []
       end
    
  end
  
  def show_many
    @expense = Expense.find(params[:id])
     @dailybank = Dailybank.find(@expense.dailybank_id)
     @expenses = Expense.where(:dailybank_id => @dailybank.id) 
     @expenses = @expenses.sort_by { |hsh| hsh[:ref] } 
     return @expenses
  end
  
  def add_new
     @dailybank = Dailybank.find(params[:id])
     ref = Expense.all.last.ref+1.to_i
     @expense = Expense.create(:dailybank_id => @dailybank.id, :ref => ref, :what => "what", :where => "where", :price => 0)
     redirect_to edit_expense_path(id: @expense.id)
  end
  
  def search
       @expenses = []
         #take params from search on Index view, or if no search, return 0
         #send to model to apply SEARCH function, which retrieves matching records 
          if params[:from]
            @dailybanks = Dailybank.search(params)
                  if @dailybanks.any?
                    # params= []
                    @expenses = @dailybanks.expenses
                   else
                    params= []
                    @expenses = 1
                  end
          else
            @expenses = 0
            params= []
          end
   
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @dailybank = Dailybank.find(params[:dailybank_id])
    ep= expense_params
    #THIS LINE OF CODE CANNOT BE SCALED UP TO MULTIPLE USERS _ NEEDS REWRITE
        if Expense.all.count ==0 
          ep[:ref] = 1001
        else
        ep[:ref] = Expense.all.last.ref+1
       end
    @expense = @dailybank.expenses.create(ep)
    redirect_to edit_dailybank_path(@dailybank)
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      
      if @expense.update(expense_params)
        format.html { redirect_to show_many_expenses_path(:id =>@expense.id), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
   
    if params.has_key?(:dailybank_id)
      @dailybank = Dailybank.find(params[:dailybank_id])
      #count = @dailybank.expenses.count
      @expense = @dailybank.expenses.find(params[:id])
      @expense.destroy
       redirect_to edit_dailybank_path(@dailybank)
    else
      @expense = Expense.find(params[:id])
      @@dailybank = Dailybank.where(:id => @expense.dailybank_id)
      Rails.logger.debug("\nXXXXXXXXX in else: #{ @@dailybank.inspect}")
      @expense.destroy
      count = Expense.where(:dailybank_id => @expense.dailybank_id).count
      if count > 0
        remaining_expense_id = Expense.where(:dailybank_id => @expense.dailybank_id).first.id
       redirect_to show_many_expenses_path(:id => remaining_expense_id), notice: 'Expense was successfully destroyed' 
     else
       if @@dailybank[0].status == "Validate and Lock"
         redirect_to edit_dailybank_path(:id => @@dailybank[0].id), notice: 'Expense was successfully destroyed' 
       elsif (@@dailybank[0].status == "Mgmt Review") || (@@dailybank[0].status == "Mgmt re-calc")
         redirect_to mgmt_review_dailybank_path(:id => @@dailybank[0].id), notice: 'Expense was successfully destroyed' 
       end
     end
    end  
  end
  
  def download_expenses_report_pdf
    @expenses_by_dailybank = params[:value]
   
    respond_to do |format|
     format.pdf do
       pdf = Prawn::Document.new
       pdf.text "Expenses Report ", size: 14, style: :bold
       pdf.text ":: HANG FIRE SOUTHERN KITCHEN :: The Pump House, Hood Road, Barry, CF62 5QN"+"\n", size: 6
       pdf.text "\n", size: 8
     
       pdf.text "Date range: " + Dailybank.where(:id => @expenses_by_dailybank.first).first.effective_date.strftime('%a, %d %b %Y') + " - " + Dailybank.where(:id => @expenses_by_dailybank.last).first.effective_date.strftime('%a, %d %b %Y'), size: 8
      pdf.text "Expenses total for this date range:" + "  "+"£#{(sprintf "%.2f", Expense.where(dailybank_id: @expenses_by_dailybank).sum(:price))}", size: 8
       pdf.text "\n"
     
       table_data_header = Array.new
       table_data_header << ["Ref", "What", "Where", "Price"]
       
       pdf.table(table_data_header) do 
          self.width = 340 
          self.cell_style = { :inline_format => true, size: 8 } 
         
          row(0).font_style = :bold
          row(0).background_color = "DDDDDD"
          columns(0).width = 40
          columns(1).width = 160
          columns(2).width = 90
          columns(3).width = 50
          columns(0..2).align = :left
          column(3).align = :right
        end
      
      @expenses_by_dailybank.each do |dailybank_id|
        dailybank = Dailybank.where(:id => dailybank_id)
        if dailybank.first.expenses.count > 0
      
      pdf.text "\n"
      pdf.text dailybank.first.effective_date.strftime('%a, %d %b %Y') ,size: 8, style: :bold 
         
       table_data = Array.new
         dailybank.first.expenses.each do |expense|
        table_data << [expense.ref.to_s, expense.what, expense.where, "£#{(sprintf "%.2f", expense.price.to_s)}"]
          end
               
        pdf.table(table_data) do 
           self.width = 340 
           self.cell_style = { :inline_format => true, size: 8 } 
        #   self.header = true
      
           columns(0).width = 40
           columns(1).width = 160
           columns(2).width = 90
           columns(3).width = 50
           columns(0..2).align = :left
           column(3).align = :right
         end
          end
          end
           pdf.text "\n", size: 12
      
        send_data pdf.render, filename: 'expenses_report.pdf', type: 'application/pdf', :disposition => 'inline'
     end
   
   end
    
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:dailybank_id, :what, :where, :price, :price, :ref)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<p>
  <strong>Expenses:</strong>
   <table>
   <tbody>
  <tr>
      <td> <%= expense.ref %></td>
      <td> <%= expense.dailybank_id %></td>
      <td> <%= expense.what %></td>
      <td> <%= expense.where %></td>
      <td> <%= number_to_currency(expense.price, :locale => :en) %></td>
      <td>  <%= link_to 'Remove', [expense.dailybank, expense], :confirm => 'Really remove expense?', :method => :delete %> </td>
   </tr> 

  </tbody>
</table>
</p>

 

app/views/expenses/_form.html.erb
<%= form_for([@dailybank, @dailybank.expenses.build]) do |f| %>
 
  <table>
    <thead>
      <tr>
        <th style="text-align:center">What</th>
        <th style="text-align:center">Where</th>
        <th style="text-align:center">Price</th>
        <th style="text-align:center"></th>
        </tr>
    </thead>
     <tbody>
    <tr> 
        <%= f.hidden_field :ref, :style => "width:74px" %>
        <%= f.hidden_field :dailybank_id, :value => @dailybank.id %>
        <td> <%= f.text_field :what, :style => "width:200px", :placeholder => "items bought" %></td>
        <td> <%= f.text_field :where, :style => "width:140px", :placeholder => "store name"  %></td>
        <td> <%= f.text_field :price, :style => "width:74px; text-align:right", :placeholder => "£0.00"  %></td>
        <td> <%= f.submit "Add Expense", class: "btn btn-warning btn-xs"  %> </td> 
     </tr> 
     </tbody>
  </table>
  </div>
<% end %>

 

app/views/expenses/edit.html.erb
<div class="row">
<div class="col-md-2">
<%= render 'layouts/sidebar' %>
</div>

<div class="col-md-10">

<h3>Edit Expense</h3>
<br>
<%= form_for(@expense) do |f| %>
 
 <h6>End of Night Record: <%= Dailybank.where(:id =>f.object.dailybank_id).first.effective_date.strftime('%A, %d %b %Y') %>
</h6>
  <table>
    <thead>
      <tr>
        <th style="text-align:center">What</th>
        <th style="text-align:center">Where</th>
        <th style="text-align:center">Price</th>
        </tr>
    </thead>
     <tbody>
    <tr> 
        <%= f.hidden_field :ref, :style => "width:74px" %>
         <td> <%= f.text_field :what, :style => "width:200px", :placeholder => "items bought" %></td>
        <td> <%= f.text_field :where, :style => "width:140px", :placeholder => "store name"  %></td>
        <td> <%= f.text_field :price, :style => "width:74px; text-align:right", :placeholder => "£0.00"  %></td>
        </tr> 
     </tbody>
  </table>
  <br>
<%= f.submit "Save Expense", class: "btn btn-warning btn-xs"  %>

<br><br><br>
<%= link_to "<< Cancel and Back to Expenses for End of Night", show_many_expenses_path(:id => f.object.id), :style => "color:orange" %>
<% end %>
</div>

app/views/expenses/index.html.erb
<div class="row">
<div class="col-md-2">
<%= render 'layouts/sidebar' %>
</div>

<div class="col-md-8">
<h3>Expenses</h3>

<%= form_tag expenses_path, method: :get, :class => "form-inline" do %>

    <h6><small>Search by:
    
     <input class="datepicker" data-provide='datepicker' id="search" name=[from] type="text" data-date-week-start=[1]  data-date-autoclose=[true] data-date-format=yyyy-mm-dd data-date-today-highlight=true class="form-control input-sm" placeholder="Search From" >
     <input class="datepicker" data-provide='datepicker' id="search" name=[to] type="text"data-date-week-start=[1]  data-date-autoclose=[true] data-date-format=yyyy-mm-dd data-date-today-highlight=true class="form-control input-sm" placeholder="Search To" >
    
  <button type="submit" class="btn btn-primary btn-sm">Search</button>
<% end %>
<br><br>

<% if @expenses_by_dailybank == 0 %>
  
  <% elsif @expenses_by_dailybank == 1 %>
  <p>No records found matching date criteria.</p>
 
  <% elsif  @expenses_by_dailybank == [] %>
  
  <% else %>
  <h4><%= link_to "Print Expenses Report", download_expenses_report_pdf_path(:value => @expenses_by_dailybank, :format => 'pdf'), :style => "color:orange" %>
  </h4>
  
  <h6> Date Range: 
  <%= Dailybank.where(:id => @expenses_by_dailybank.first).first.effective_date.strftime('%a, %d %b %Y')%>
   - 
    <%= Dailybank.where(:id => @expenses_by_dailybank.last).first.effective_date.strftime('%a, %d %b %Y')%>
  <br>  <br>
  Expenses Total for this date range: <%= number_to_currency(Expense.where(dailybank_id: @expenses_by_dailybank).sum(:price), :locale => :en) %></h6>
  <hr>
  <% @expenses_by_dailybank.each do |dailybank| %>
    <% if dailybank.expenses.count > 0%>
    
<table class= "table table-condensed">
  <thead>
    <tr>
      <th style="width: 10%">Ref</th>
      <th style="width: 30%">What</th>
      <th style="width: 20%">Where</th>
      <th style="width: 10%">Price</th>
      <th style="width: 30%" colspan="2"></th>
    </tr>
  </thead>
 <%= dailybank.effective_date.strftime('%a, %d %b %Y')  %> - <b><%= a = dailybank.status %></b> - <%= link_to 'See End of Night Record', dailybank_path(dailybank), :style => "color:orange" %>
  <tbody>

    <% dailybank.expenses.each do |expense| %>
      <tr>
        <td><%= expense.ref %></td>
        <td><%= expense.what %></td>
        <td><%= expense.where %></td>
        <td><%= number_to_currency(expense.price, :locale => :en) %></td>
        
        <% if a == "Locked" %>
          <td colspan="2">Record cannot be edited.</td>
          <% else %>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% end %>
      </tr>
    <% end %>    <% end %>
  </tbody>
</table>
<% end %>
<% end %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<div class="row">
<div class="col-md-2">
<%= render 'layouts/sidebar' %>
</div>

<div class="col-md-10">

<br><br><br><br>
<p>
  <strong>Dailybank:</strong>
  <%= @expense.dailybank_id %>
</p>

<p>
  <strong>What:</strong>
  <%= @expense.what %>
</p>

<p>
  <strong>Where:</strong>
  <%= @expense.where %>
</p>

<p>
  <strong>Price:</strong>
  <%= @expense.price %>
</p>


<p>
  <strong>Ref:</strong>
  <%= @expense.ref %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>
</div>

app/views/expenses/show_many.html.erb
<div class="row">
<div class="col-md-2">
<%= render 'layouts/sidebar' %>
</div>

<div class="col-md-8">
<h3>Expenses</h3>
<br>

<table class= "table table-condensed">
  <thead>
    <tr>
      <th style="width: 10%">Ref</th>
      <th style="width: 30%">What</th>
      <th style="width: 20%">Where</th>
      <th style="width: 10%">Price</th>
      <th style="width: 30%" colspan="2"></th>
    </tr>
  </thead>
<h6> <%= Dailybank.where(:id => @expenses.first.dailybank_id).first.effective_date.strftime('%a, %d %b %Y')  %> - <b><%= a= Dailybank.where(:id => @expenses.first.dailybank_id).first.status %></b>  </h6>
  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.ref %></td>
        <td><%= expense.what %></td>
        <td><%= expense.where %></td>
        <td><%= number_to_currency(expense.price, :locale => :en) %></td>
        
        <% if a == "Locked" %>
          <td colspan="2">Record cannot be edited.</td>
          <% else %>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '<< Back to  End of Night Record', dailybank_path(@expenses.first.dailybank_id), :style => "color:orange" %>
 | <%= link_to "Add Expense", add_new_expenses_path(:id => @dailybank.id), :class => "btn btn-xs btn-success", :style => "color:black" %>